# Build Stage
FROM golang:1.9.2-stretch AS build-stage

LABEL app="build-go-chatbot-lab"
LABEL REPO="https://github.com/bossjones/go-chatbot-lab"

ENV GOROOT=/usr/lib/go \
    GOPATH=/go \
    GOBIN=/go/bin \
    PROJPATH=/go/src/github.com/bossjones/go-chatbot-lab

# Because of https://github.com/docker/docker/issues/14914
ENV PATH=$PATH:$GOROOT/bin:$go/bin

ADD . /go/src/github.com/bossjones/go-chatbot-lab
WORKDIR /go/src/github.com/bossjones/go-chatbot-lab

RUN make build-alpine
